stages:
  make_dataset:
    desc: Download data from Kaggle
    cmd: python3 src/data/make_dataset.py -c house-prices-advanced-regression-techniques
      -tr train.csv -te test.csv -o ./data/raw
    deps:
    - src/data/make_dataset.py
    outs:
    - data/raw/test.csv
    - data/raw/train.csv
  encode_labels:
    desc: Convert categorical labels to integer values without drop original columns
    cmd: python3 src/data/encode_labels.py -tr data/interim/train_nan_imputed.csv
      -te data/interim/test_nan_imputed.csv -o data/interim
    deps:
    - data/interim/test_nan_imputed.csv
    - data/interim/train_nan_imputed.csv
    - src/data/encode_labels.py
    params:
    - encoding
    outs:
    - data/interim/test_categorized.csv
    - data/interim/train_categorized.csv
  impute_nan:
    desc: Replace missing values using mean strategy
    cmd: python3 src/data/replace_nan.py -tr data/interim/train_outliers_removed.csv
      -te data/interim/test_outliers_removed.csv -o data/interim
    deps:
    - data/interim/test_outliers_removed.csv
    - data/interim/train_outliers_removed.csv
    - src/data/replace_nan.py
    params:
    - ignore_cols
    - imputation
    outs:
    - data/interim/test_nan_imputed.csv
    - data/interim/train_nan_imputed.csv
  remove_outliers:
    desc: Remove outliers values
    cmd: python3 src/data/remove_outliers.py -tr data/raw/train.csv -te data/raw/test.csv
      -o data/interim
    deps:
    - data/raw/test.csv
    - data/raw/train.csv
    - src/data/remove_outliers.py
    params:
    - target_class
    - is_drop_outlier
    outs:
    - data/interim/test_outliers_removed.csv
    - data/interim/train_outliers_removed.csv
  skew_data:
    desc: Skewness values with threshold
    cmd: python3 src/data/skew_data.py -tr data/interim/train_categorized.csv -te
      data/interim/test_categorized.csv -o data/interim
    deps:
    - data/interim/test_categorized.csv
    - data/interim/train_categorized.csv
    - src/data/skew_data.py
    params:
    - skew
    outs:
    - data/interim/test_skewed.csv
    - data/interim/train_skewed.csv
  train_model:
    desc: Train model
    cmd: python3 src/models/train_model.py -tr data/interim/train_skewed.csv -rd ./results
      -md ./models
    deps:
    - data/interim/train_skewed.csv
    - src/models/train_model.py
    params:
    - model_params
    - target_class
  predict_model:
    desc: Use trained models to make predictions
    cmd: python3 src/models/predict_model.py -te data/interim/test_skewed.csv -rd
      ./submissions -md ./models
    deps:
    - data/interim/test_skewed.csv
    - src/models/predict_model.py
    params:
    - target_class
