target_class: SalePrice

ignore_cols:
- Id
- SalePrice

is_drop_outlier: true

imputation:
  method: mean

encoding:
  binary_to_numerical_cols:
  - CentralAir

skew:
  is_transform: true
  threshold: 0.5

model_params:
  xgb_regressor:
    colsample_bytree: 0.4603
    gamma: 0.0468
    learning_rate: 0.05
    max_depth: 3
    min_child_weight: 1.7817
    n_estimators: 2200
    reg_alpha: 0.4640
    reg_lambda: 0.8571
    subsample: 0.5213
    silent: 1
  svr:
    C: 11
    epsilon: 0.009
    gamma: 0.0003
    kernel: 'rbf'
  lasso:
    alpha: 0.0005
    max_iter: 10000
  ridge:
    alpha: 35.0
  kernel_ridge:
    alpha: 0.4
    coef0: 1
    degree: 3
    kernel: 'polynomial'
  elastic_net:
    alpha: 0.004
    l1_ratio: 0.1
    max_iter: 10000
  gradient_boosting_regressor:
    n_estimators: 3000
    learning_rate: 0.05
    max_depth: 4
    max_features: 'sqrt'
    min_samples_leaf: 15
    min_samples_split: 10
    loss: 'huber'
    random_state: 5
